name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - run: composer install
        name: Composer

      - run: make phpstan
        name: PHPStan

      - run: make cs
        name: Code-Style

      - run: make unit-tests
        name: Unit Tests
