name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - run: composer install
        name: Composer

      - run: vendor/bin/phpstan analyse -l 8 src/ --output=github
        name: PHPStan

      - run: vendor/bin/phpcs src --standard=vendor/pd/coding-standard/src/PeckaCodingStandard/ruleset.xml
        name: Code-Style
